name: scheduled-work-flow
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        echo 'work flow schedule triggered'
